config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  resources :clientzs
  get 'welcome/homepage'
  get 'welcome/acc'
  get 'welcome/gal'
  get 'welcome/loc'
  get 'welcome/act'

  root 'welcome#homepage'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/clientz.rb
class Clientz < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Message was successfully Sent, We will get back to You as soon as Possible.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :tel, :start, :end, :rooms, :adults, :message)
    end
end

app/controllers/clientzs_controller.rb
class ClientzsController < ApplicationController
  before_action :set_clientz, only: [:show, :edit, :update, :destroy]

  # GET /clientzs
  # GET /clientzs.json
  def index
    @clientzs = Clientz.all
  end

  # GET /clientzs/1
  # GET /clientzs/1.json
  def show
  end

  # GET /clientzs/new
  def new
    @clientz = Clientz.new
  end

  # GET /clientzs/1/edit
  def edit
  end

  # POST /clientzs
  # POST /clientzs.json
  def create
    @clientz = Clientz.new(clientz_params)

    respond_to do |format|
      if @clientz.save
        format.html { redirect_to @clientz, notice: 'Clientz was successfully created.' }
        format.json { render :show, status: :created, location: @clientz }
      else
        format.html { render :new }
        format.json { render json: @clientz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientzs/1
  # PATCH/PUT /clientzs/1.json
  def update
    respond_to do |format|
      if @clientz.update(clientz_params)
        format.html { redirect_to @clientz, notice: 'Clientz was successfully updated.' }
        format.json { render :show, status: :ok, location: @clientz }
      else
        format.html { render :edit }
        format.json { render json: @clientz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientzs/1
  # DELETE /clientzs/1.json
  def destroy
    @clientz.destroy
    respond_to do |format|
      format.html { redirect_to clientzs_url, notice: 'Clientz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clientz
      @clientz = Clientz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clientz_params
      params.require(:clientz).permit(:name, :email, :tel, :start, :end, :rooms, :adults, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end

  def acc
  end

   def gal
  end

  def loc
  end

  def act
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/clientzs_helper.rb
module ClientzsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client, html: { multipart: true }) do |f| %>
  <% if @client.errors.any? %>
   

      <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h4>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="container">
    <div class="row">
    <div class="col-lg-6 col-sm-12">

   <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :tel %><br>
    <%= f.text_field :tel, class: "form-control" %>
  </div>



 <div class="form-group">
    <%= f.label :Arrival  %><br>
    <%= f.date_select :start, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :Departure  %><br>
    <%= f.date_select :end, class: "form-control" %>
  </div>
  </div>
   
   <div class="col-lg-6 col-sm-12">
  <div class="form-group">
<<<<<<< HEAD
    <%= f.label :Children_Below_5 %><br>
=======
    <%= f.label :Rooms %><br>
>>>>>>> ba70615998eb8ee1ccc7175cd66a79d07f621079
    <%= f.number_field :rooms, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :Adults %><br>
    <%= f.number_field :adults, class: "form-control" %>
  </div>

<<<<<<< HEAD
   <div class="form-group">
    <%= f.label :Room %><br>
    <%= f.select :room, ['option1', 'option2']%>
  </div>



  <div class="form-group">
    <%= f.label :Other_Additional_Facilities_If_Required %><br>
=======


  <div class="form-group">
    <%= f.label :Other_Details %><br>
>>>>>>> ba70615998eb8ee1ccc7175cd66a79d07f621079
    <%= f.text_area :message, class: "form-control" %>
  </div>
   <div class="form-group">
     <%= f.submit :value => "Submit", class: "btn btn-primary" %>
  </div>
  
  </div></div></div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/creative.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/welcome/homepage" style="color: black">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about" style="color: black">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/acc" style="color: black">Accomodation</a>
                    </li>
                    <li>
                       <a class="page-scroll" href="/welcome/gal" style="color: black">Gallery</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact" style="color: black">Contact</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="/clients/new" style="color: black">Reservations</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/loc" style="color: black">Location</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/act" style="color: black">Things To Do</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<div class="container">
  <h2 class="center">Reservations</h2>



  <div class="row" >
    <% @clients.each do |client| %>
      
        <p>Name: <%= client.name %></p>
        <p>Email: <%= client.email %></p>
        <p>Tel: <%= client.tel %></p>
        <p>Arrival Date: <%= client.start %></p>
        <p>Departure Date: <%= client.end %></p>
        <p>Number Of Rooms: <%= client.rooms %></p>
        <p>Number Of Adults: <%= client.adults %></p>
        <p>Other Details: <%= client.message %></p>
        <p><% link_to 'Show', client %></p>
        <p><% link_to 'Edit', edit_client_path(client) %></p>
        <p><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <br><br>
     
    <% end %>
  </div>
</div>

<br><br>

<% link_to '', new_client_path %>


<section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>+256 (0) 785 803 728</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@riftvalleygamelodge.com</a></p>
                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>

</html>

app/views/clients/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/creative.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/welcome/homepage" style="color: black">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about" style="color: black">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/acc" style="color: black">Accomodation</a>
                    </li>
                    <li>
                       <a class="page-scroll" href="/welcome/gal" style="color: black">Gallery</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact" style="color: black">Contact</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="/clients/new" style="color: black">Reservations</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/loc" style="color: black">Location</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/act" style="color: black">Things To Do</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

 
</br>
                     </br>
                      </br>
  
<%= render 'form' %>

<% link_to 'Back', clients_path %>












    <!--<aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
            </div>
        </div>
    </aside>-->

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>+256 (0) 785 803 728</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@riftvalleygamelodge.com</a></p>
                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>

</html>

app/views/clients/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/creative.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/welcome/homepage" style="color: black">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about" style="color: black">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/acc" style="color: black">Accomodation</a>
                    </li>
                    <li>
                       <a class="page-scroll" href="/welcome/gal" style="color: black">Gallery</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact" style="color: black">Contact</a>
                    </li>
                     <li>
                        <a class="page-scroll" href="/clients/new" style="color: black">Reservations</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/loc" style="color: black">Location</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/act" style="color: black">Things To Do</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

 
</br>
                     </br>
                      </br>


<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
    <div class="col-lg-6 col-sm-12">

<p>
  <strong>Name:</strong>
  <% @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @client.tel %>
</p>

<p>
  <strong>Arrival Date:</strong>
  <%= @client.start %>
</p>

<p>
  <strong>Departure Date:</strong>
  <%= @client.end %>
</p>
</div>
   
   <div class="col-lg-6 col-sm-12">
<p>
<<<<<<< HEAD
  <strong>Children Below 5:</strong>
=======
  <strong>Rooms:</strong>
>>>>>>> ba70615998eb8ee1ccc7175cd66a79d07f621079
  <%= @client.rooms %>
</p>

<p>
  <strong>Adults:</strong>
  <%= @client.adults %>
</p>

<p>
<<<<<<< HEAD
  <strong>Room:</strong>
  <%= @client.room %>
</p>

<p>
=======
>>>>>>> ba70615998eb8ee1ccc7175cd66a79d07f621079
  <strong>Other Details:</strong>
  <%= @client.message %>
</p>
</div>

<% link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', new_client_path %>

<section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>+256 (0) 785 803 728</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@riftvalleygamelodge.com</a></p>
                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>

</html>

app/views/clientzs/_form.html.erb
<%= form_for(@clientz) do |f| %>
  <% if @clientz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clientz.errors.count, "error") %> prohibited this clientz from being saved:</h2>

      <ul>
      <% @clientz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.date_select :end %>
  </div>
  <div class="field">
    <%= f.label :rooms %><br>
    <%= f.number_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :adults %><br>
    <%= f.number_field :adults %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientzs/edit.html.erb
<h1>Editing Clientz</h1>

<%= render 'form' %>

<%= link_to 'Show', @clientz %> |
<%= link_to 'Back', clientzs_path %>

app/views/clientzs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clientzs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th>Start</th>
      <th>End</th>
      <th>Rooms</th>
      <th>Adults</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientzs.each do |clientz| %>
      <tr>
        <td><%= clientz.name %></p>
        <td><%= clientz.email %></p>
        <td><%= clientz.tel %></p>
        <td><%= clientz.start %></p>
        <td><%= clientz.end %></p>
        <td><%= clientz.rooms %></p>
        <td><%= clientz.adults %></p>
        <td><%= clientz.message %></p>
        <td><%= link_to 'Show', clientz %></p>
        <td><%= link_to 'Edit', edit_clientz_path(clientz) %></p>
        <td><%= link_to 'Destroy', clientz, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clientz', new_clientz_path %>

app/views/clientzs/new.html.erb
<h1>New Clientz</h1>

<%= render 'form' %>

<%= link_to 'Back', clientzs_path %>

app/views/clientzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clientz.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @clientz.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @clientz.tel %>
</p>

<p>
  <strong>Start:</strong>
  <%= @clientz.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @clientz.end %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @clientz.rooms %>
</p>

<p>
  <strong>Adults:</strong>
  <%= @clientz.adults %>
</p>

<p>
  <strong>Message:</strong>
  <%= @clientz.message %>
</p>

<%= link_to 'Edit', edit_clientz_path(@clientz) %> |
<%= link_to 'Back', clientzs_path %>